services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000' # [host_port]:[container_port]
    volumes:
      # This line creates a bind mount volume, which links the current directory to the /usr/src/app directory 
      # in the container. This means that any changes made to the files in the current directory will be reflected
      # in the container, and vice versa in real time.
      - .:/usr/src/app 
  mongo:
    image: mongo
  